// Clareo brand palette.
//
// Curated in families that harmonise with the warm paper/ink base
// (paper #F5F1EB / ink #1A1D24). The ethos is editorial: pigments
// over primaries, dusty over candy, sun-bleached over neon. Everything
// is picked to sit on cream paper next to deep ink without vibrating.
//
// This module is the single source of truth for both the website and
// the app. The web mirrors these into CSS variables via
// `dist/tokens.css` (regenerated by `npm run build:css`); the app
// consumes the JS values directly through the theme layer.

export const neutral = {
  paper: '#F5F1EB',
  bone: '#EBE3D6',
  chalk: '#D4CCBF',
  ash: '#A8A198',
  charcoal: '#3B3833',
  ink: '#1A1D24',
};

export const warm = {
  ochre: '#B88A3A',
  saffron: '#D99545',
  marigold: '#E8A94E',
  clay: '#B46A4A',
  terracotta: '#C25C3F',
  ember: '#9E3F2B',
};

export const cool = {
  sage: '#A5AD97',
  eucalyptus: '#7A9187',
  teal: '#3E7A78',
  lagoon: '#4C8896',
  steel: '#6B7681',
  slateBlue: '#56677E',
};

export const deep = {
  forest: '#2C4A38',
  moss: '#455B3E',
  midnight: '#1B2948',
  petrol: '#1E3A42',
  aubergine: '#3A2438',
  umber: '#3C2E24',
};

export const expressive = {
  coral: '#E37259',
  vermilion: '#D6463A',
  rose: '#D4848F',
  plum: '#78456A',
  iris: '#6E6AB8',
  cobalt: '#2F4BA5',
};

export const muted = {
  sand: '#D4C6AC',
  stone: '#A79E90',
  olive: '#7B7A5A',
  dustyBlue: '#8EA0B2',
  fadedDenim: '#6C849E',
  smoke: '#87857E',
};

export const palette = {
  neutral,
  warm,
  cool,
  deep,
  expressive,
  muted,
};

// Editorial fallback-cover palette: a curated subset for things like
// auto-coloured book covers or category accents. Picked so any pair
// looks intentional next to each other on cream paper.
export const accentRotation = [
  expressive.cobalt,
  warm.terracotta,
  cool.teal,
  deep.aubergine,
  expressive.plum,
  warm.ochre,
  cool.lagoon,
  deep.petrol,
  expressive.iris,
  warm.clay,
  cool.eucalyptus,
  deep.forest,
];

// rgba helper: write `rgba('#1A1D24', 0.5)` and forget about hex math.
export function rgba(hex, alpha) {
  const h = hex.replace('#', '');
  const full = h.length === 3
    ? h.split('').map((c) => c + c).join('')
    : h;
  const r = parseInt(full.slice(0, 2), 16);
  const g = parseInt(full.slice(2, 4), 16);
  const b = parseInt(full.slice(4, 6), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

export default palette;
